title: 'pyramiden.net'
url: https://pyramiden.net

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  title: ':title - page :num'
  permalink: 'page:num/'
  trail:
    before: 1
    after: 1
  sort_field: 'date'
  sort_reverse: true
  


permalink: /blog/:year/:title:output_ext
